#stage 1 - compile angular app
FROM node:19-alpine as builder

WORKDIR /app
COPY . .
RUN npm install
RUN apk add jq
RUN chmod +x ./setup_environment.sh && ./setup_environment.sh
RUN npm run build --prod

# stage 2 copy dist to small nginx server...
FROM nginx:alpine

COPY --from=builder /app/dist/frontend /user/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
