export const THEMES:any = {
  Dyslexia: {
      primaryColor: 'var(--primary)',
      secondaryColor: 'var(--secondary)',
      tertiaryColor: 'var(--dm-tertiary-300)',
      textOnTertiary: 'var(--dm-on-tertiary-300)',
      textOnPrimary: 'var(--on-primary)',
      textOnSecondary: 'var(--on-secondary)',
      background: 'var(--background)',
    },
    BDyslexia: {
      primaryColor: '#311B14',
      secondaryColor: 'var(--primaryDarkBG)',
      tertiaryColor: 'var(--primary)',
      textOnTertiary: 'var(--dm-on-tertiary-300)',
      textOnPrimary: 'var(--on-primary)',
      textOnSecondary: 'var(--dm-on-background-secondary)',
      background: 'black',
    },
    Default: {
      primaryColor: '#435f7a',
      secondaryColor: '#fff',
      textOnPrimary: '#f5f5f5',
      tertiaryColor: 'rgba(18, 177, 245, 0.409)',
      textOnTertiary: 'hsl(0, 0%, 100%)',
      textOnSecondary: 'black',
      background: '#E6EAEA',
    },
    BDefault: {
      primaryColor: 'var(--primaryDarkBG)',
      secondaryColor: '#0A2647',
      textOnPrimary: '#f5f5f5',
      tertiaryColor: 'rgba(18, 177, 245, 0.409)',
      textOnTertiary: 'hsl(0, 0%, 100%)',
      textOnSecondary: 'white',
      background: 'black',
    },
    'BColor Blindness': {
      primaryColor: '#8a660d9c',
      secondaryColor: 'black',
      textOnPrimary: ' var(--on-primary)',
      textOnSecondary: 'white',
      tertiaryColor: '#9E6F21',
      textOnTertiary: 'var(--cb-textOnTertiary)',
      background: 'var(--primaryDarkBG)',
    },
    'Color Blindness': {
      primaryColor: 'var(--cb-primary)',
      secondaryColor: 'var(--cb-secondary)',
      textOnPrimary: ' var(--cb-textOnPrimary)',
      textOnSecondary: 'var(--cb-textOnSecondary)',
      tertiaryColor: '#EBB02D',
      textOnTertiary: 'var(--cb-textOnTertiary)',
      background: '#E6EAEA',
    },
    BAutism: {
      primaryColor: '#40513B',
      secondaryColor: 'black',
      textOnPrimary: ' #FFFFFF',
      textOnSecondary: 'var(--at-secondary)',
      tertiaryColor: 'var(--at-tertiary)',
      textOnTertiary: 'var(--at-textOnTertiary)',
      background: 'var(--primaryDarkBG)',
    },
    Autism: {
      primaryColor: 'var(--at-primary)',
      secondaryColor: 'var(--at-secondary)',
      textOnPrimary: ' #FFFFFF',
      textOnSecondary: 'var(--at-textOnSecondary)',
      tertiaryColor: 'var(--at-tertiary)',
      textOnTertiary: 'var(--at-textOnTertiary)',
      background: 'var(--background)',
    },
    
  };

