from enum import Enum


class Document(Enum):
    INSURANCE = 'INSURANCE'
    LAND = 'LAND'
    SERVICE_CONTRACT = 'SERVICE_CONTRACT'
    EMPLOYMENT_CONTRACT = 'EMPLOYMENT_CONTRACT'
    CONFIDENTIALITY_AGREEMENT = 'CONFIDENTIALITY_AGREEMENT'
    SALES_CONTRACT = 'SALES_CONTRACT'
    INDEPENDENT_CONTRACTOR_AGREEMENT = 'INDEPENDENT_CONTRACTOR_AGREEMENT'
    LOAN_AGREEMENT = 'LOAN_AGREEMENT'
    PARTNERSHIP_AGREEMENT = 'PARTNERSHIP_AGREEMENT'